# Generated by Django 4.0.6 on 2022-07-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Custom',
            fields=[
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('username', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254, unique=b'I01\n')),
                ('password', models.CharField(max_length=8)),
                ('line1', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=8)),
                ('state', models.CharField(max_length=8)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
